import type { Category, MenuItem, Restaurant, TableInfo } from "./types";

export const restaurant: Restaurant = {
  slug: "kesar-tandoor",
  name: "Kesar Tandoor",
  tagline: "North Indian · Charcoal grill",
  logoSrc: "/kesar-tandoor.svg",
  fssai: "11522004000237",
  gstPercent: 5,
  serviceHours: "12:00 pm – 11:30 pm",
  isOpen: true,
  currency: "₹",
};

export const table: TableInfo = {
  token: "A7X29K",
  number: "12",
  seats: 4,
  section: "Garden side",
};

export const categories: Category[] = [
  { id: "starters", name: "Starters" },
  { id: "tandoor", name: "Tandoor" },
  { id: "mains", name: "Main Course" },
  { id: "breads", name: "Breads" },
  { id: "rice", name: "Rice & Biryani" },
  { id: "desserts", name: "Desserts" },
  { id: "drinks", name: "Beverages" },
];

const spiceOptions = {
  id: "spice",
  label: "Spice level",
  required: true,
  choices: [
    { id: "mild", label: "Mild", priceDelta: 0 },
    { id: "medium", label: "Medium", priceDelta: 0 },
    { id: "hot", label: "Hot", priceDelta: 0 },
  ],
};

const portionOptions = {
  id: "portion",
  label: "Portion",
  required: true,
  choices: [
    { id: "half", label: "Half", priceDelta: 0 },
    { id: "full", label: "Full", priceDelta: 120 },
  ],
};

export const menuItems: MenuItem[] = [
  // ---------------------------------------------------------------- Starters
  {
    id: "paneer-tikka",
    name: "Paneer Tikka",
    description: "Charred cottage cheese, hung curd and ajwain.",
    price: 340,
    diet: "veg",
    categoryId: "starters",
    prepMinutes: 18,
    available: true,
    bestseller: true,
    spiceLevel: 2,
    swatch: ["#E9A23B", "#C2571F"],
    glyph: "🧀",
    options: [spiceOptions],
  },
  {
    id: "dahi-ke-kebab",
    name: "Dahi Ke Kebab",
    description: "Crisp yoghurt kebabs. Delicate — eat hot.",
    price: 310,
    diet: "veg",
    categoryId: "starters",
    prepMinutes: 15,
    available: true,
    spiceLevel: 1,
    swatch: ["#F0D9A8", "#C89A4E"],
    glyph: "🥟",
  },
  {
    id: "amritsari-macchi",
    name: "Amritsari Macchi",
    description: "Sole in carom batter, fried crisp.",
    price: 480,
    diet: "nonveg",
    categoryId: "starters",
    prepMinutes: 20,
    available: true,
    spiceLevel: 2,
    swatch: ["#E4B457", "#A65B22"],
    glyph: "🐟",
  },
  {
    id: "chilli-mushroom",
    name: "Chilli Mushroom",
    description: "Tossed with pepper, garlic and soy.",
    price: 290,
    diet: "veg",
    categoryId: "starters",
    prepMinutes: 14,
    available: false,
    spiceLevel: 3,
    swatch: ["#B4703C", "#5E3218"],
    glyph: "🍄",
  },

  // ---------------------------------------------------------------- Tandoor
  {
    id: "murgh-malai-tikka",
    name: "Murgh Malai Tikka",
    description: "Cream cheese and cardamom. Mild, smoky.",
    price: 460,
    diet: "nonveg",
    categoryId: "tandoor",
    prepMinutes: 22,
    available: true,
    bestseller: true,
    spiceLevel: 1,
    swatch: ["#F2DFB8", "#C79A5B"],
    glyph: "🍗",
    options: [portionOptions],
  },
  {
    id: "tandoori-chicken",
    name: "Tandoori Chicken",
    description: "Kashmiri chilli, mustard oil, on the bone.",
    price: 520,
    diet: "nonveg",
    categoryId: "tandoor",
    prepMinutes: 28,
    available: true,
    spiceLevel: 2,
    swatch: ["#D9542B", "#8C2410"],
    glyph: "🔥",
    options: [portionOptions],
  },
  {
    id: "tandoori-broccoli",
    name: "Tandoori Broccoli",
    description: "Cheddar and mustard, blistered over charcoal.",
    price: 380,
    diet: "veg",
    categoryId: "tandoor",
    prepMinutes: 18,
    available: true,
    spiceLevel: 1,
    swatch: ["#7FA84C", "#3D5B21"],
    glyph: "🥦",
  },
  {
    id: "seekh-kebab",
    name: "Mutton Seekh Kebab",
    description: "Minced lamb, brown onion, garam masala.",
    price: 540,
    diet: "nonveg",
    categoryId: "tandoor",
    prepMinutes: 25,
    available: true,
    spiceLevel: 2,
    swatch: ["#A0522D", "#5A2A14"],
    glyph: "🍢",
  },

  // ---------------------------------------------------------------- Mains
  {
    id: "dal-makhani",
    name: "Dal Makhani",
    description: "Black urad simmered twenty-four hours.",
    price: 380,
    diet: "veg",
    categoryId: "mains",
    prepMinutes: 12,
    available: true,
    bestseller: true,
    spiceLevel: 1,
    swatch: ["#7A5236", "#3A2114"],
    glyph: "🍲",
  },
  {
    id: "butter-chicken",
    name: "Butter Chicken",
    description: "Tomato and cashew gravy, finished with methi.",
    price: 520,
    diet: "nonveg",
    categoryId: "mains",
    prepMinutes: 18,
    available: true,
    bestseller: true,
    spiceLevel: 1,
    swatch: ["#E2703A", "#A8380F"],
    glyph: "🍛",
    options: [spiceOptions],
  },
  {
    id: "paneer-lababdar",
    name: "Paneer Lababdar",
    description: "Twice-cooked onion-tomato masala.",
    price: 430,
    diet: "veg",
    categoryId: "mains",
    prepMinutes: 16,
    available: true,
    spiceLevel: 2,
    swatch: ["#E08B4A", "#9C4415"],
    glyph: "🥘",
    options: [spiceOptions],
  },
  {
    id: "laal-maas",
    name: "Laal Maas",
    description: "Mathania chillies and garlic. Genuinely hot.",
    price: 640,
    diet: "nonveg",
    categoryId: "mains",
    prepMinutes: 26,
    available: true,
    spiceLevel: 3,
    swatch: ["#C0341C", "#6B1508"],
    glyph: "🌶️",
  },

  // ---------------------------------------------------------------- Breads
  {
    id: "butter-naan",
    name: "Butter Naan",
    description: "Off the tandoor wall, brushed with butter.",
    price: 80,
    diet: "veg",
    categoryId: "breads",
    prepMinutes: 8,
    available: true,
    swatch: ["#EBD7A9", "#C09A55"],
    glyph: "🫓",
  },
  {
    id: "laccha-paratha",
    name: "Laccha Paratha",
    description: "Hand-coiled, pulls apart in sheets.",
    price: 95,
    diet: "veg",
    categoryId: "breads",
    prepMinutes: 10,
    available: true,
    swatch: ["#DEBE84", "#A67B36"],
    glyph: "🥯",
  },
  {
    id: "garlic-kulcha",
    name: "Garlic Kulcha",
    description: "Stuffed with potato and coriander.",
    price: 110,
    diet: "veg",
    categoryId: "breads",
    prepMinutes: 12,
    available: true,
    bestseller: true,
    swatch: ["#E7CE97", "#B08A3E"],
    glyph: "🧄",
  },
  {
    id: "tandoori-roti",
    name: "Tandoori Roti",
    description: "Plain whole wheat, clay oven.",
    price: 55,
    diet: "veg",
    categoryId: "breads",
    prepMinutes: 7,
    available: true,
    swatch: ["#D2B27C", "#8E6B2C"],
    glyph: "🍞",
  },

  // ---------------------------------------------------------------- Rice
  {
    id: "hyderabadi-biryani",
    name: "Mutton Biryani",
    description: "Sealed and dum-cooked. Serves two.",
    price: 620,
    diet: "nonveg",
    categoryId: "rice",
    prepMinutes: 35,
    available: true,
    bestseller: true,
    spiceLevel: 2,
    swatch: ["#D9A441", "#8A5410"],
    glyph: "🍚",
  },
  {
    id: "subz-biryani",
    name: "Subz Biryani",
    description: "Saffron milk and fried onion. Serves two.",
    price: 480,
    diet: "veg",
    categoryId: "rice",
    prepMinutes: 30,
    available: true,
    spiceLevel: 1,
    swatch: ["#E3C066", "#9C7420"],
    glyph: "🍛",
  },
  {
    id: "jeera-rice",
    name: "Jeera Rice",
    description: "Basmati tempered with cumin and ghee.",
    price: 220,
    diet: "veg",
    categoryId: "rice",
    prepMinutes: 12,
    available: true,
    swatch: ["#EFE3C4", "#C0AC7A"],
    glyph: "🍘",
  },

  // ---------------------------------------------------------------- Desserts
  {
    id: "gulab-jamun",
    name: "Gulab Jamun",
    description: "Warm khoya dumplings. Two pieces.",
    price: 180,
    diet: "veg",
    categoryId: "desserts",
    prepMinutes: 6,
    available: true,
    swatch: ["#A9642C", "#5C2E0E"],
    glyph: "🍮",
  },
  {
    id: "shahi-tukda",
    name: "Shahi Tukda",
    description: "Saffron rabdi and pistachio.",
    price: 220,
    diet: "veg",
    categoryId: "desserts",
    prepMinutes: 10,
    available: true,
    bestseller: true,
    swatch: ["#EFCE84", "#B98B2E"],
    glyph: "🍰",
  },
  {
    id: "kulfi-falooda",
    name: "Kulfi Falooda",
    description: "Vermicelli, basil seed and rose.",
    price: 210,
    diet: "veg",
    categoryId: "desserts",
    prepMinutes: 5,
    available: true,
    swatch: ["#F0C9D2", "#C06B84"],
    glyph: "🍧",
  },

  // ---------------------------------------------------------------- Drinks
  {
    id: "masala-chaas",
    name: "Masala Chaas",
    description: "Buttermilk with cumin and curry leaf.",
    price: 120,
    diet: "veg",
    categoryId: "drinks",
    prepMinutes: 4,
    available: true,
    swatch: ["#E8EDDC", "#A8B58C"],
    glyph: "🥛",
  },
  {
    id: "sweet-lassi",
    name: "Sweet Lassi",
    description: "Thick set curd, topped with malai.",
    price: 150,
    diet: "veg",
    categoryId: "drinks",
    prepMinutes: 5,
    available: true,
    bestseller: true,
    swatch: ["#F6EBD2", "#CBB278"],
    glyph: "🥤",
  },
  {
    id: "nimbu-soda",
    name: "Nimbu Soda",
    description: "Fresh lime, black salt and soda.",
    price: 110,
    diet: "veg",
    categoryId: "drinks",
    prepMinutes: 3,
    available: true,
    swatch: ["#D6E88C", "#8CA33A"],
    glyph: "🍋",
  },
  {
    id: "kesar-chai",
    name: "Kesar Chai",
    description: "Saffron, green cardamom, full-fat milk.",
    price: 90,
    diet: "veg",
    categoryId: "drinks",
    prepMinutes: 6,
    available: true,
    swatch: ["#DDA85C", "#9A6520"],
    glyph: "☕",
  },
];

/** The URL a printed table QR resolves to. */
export function tableUrl(slug: string, token: string) {
  return `https://tandoorline.app/r/${slug}/t/${token}`;
}
